RACKSPACE_MAILBOX_HEADERS = [
    "Username",
    "Password",
    "Enabled",
    "FirstName",
    "MiddleInitial",
    "LastName",
    "AlternateEmail",
    "Organization",
    "Department",
    "Title",
    "MobilePhoneNumber",
    "BusinessPhoneNumber",
    "Street",
    "City",
    "State",
    "PostalCode",
    "Country",
    "Notes",
    "UserID",
    "CustomID",
    "VisibleInCompanyDirectory",
    "VisibleInGAL",
]


def rackspace_row(user: dict, password: str) -> list[str]:
    return [
        user["source_email"],
        password,
        "TRUE",
        user.get("first_name") or "",
        "",
        user.get("last_name") or "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "TRUE",
        "TRUE",
    ]
